# Generated by Django 5.2.3 on 2025-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Environment",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=32, unique=True, verbose_name="环境名称"
                    ),
                ),
                (
                    "url",
                    models.CharField(max_length=255, null=True, verbose_name="环境URL"),
                ),
                ("remark", models.TextField(null=True, verbose_name="备注")),
            ],
            options={
                "verbose_name": "环境表",
                "db_table": "environment",
            },
        ),
    ]
