# Generated by Django 5.2.4 on 2025-08-27 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0004_alter_apicasemodule_project"),
        ("config", "0001_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="environment",
            name="type",
            field=models.IntegerField(
                choices=[(0, "局部环境"), (1, "全局环境")],
                default=1,  # 设置默认值为全局环境
                help_text="0=局部环境, 1=全局环境",
                verbose_name="环境类型",
            ),
        ),
        migrations.AddField(
            model_name="environment",
            name="variables",
            field=models.JSONField(
                default=dict,
                help_text="格式: {变量名: {value: 值, description: 描述}}",
                verbose_name="环境变量",
            ),
        ),
        migrations.CreateModel(
            name="CaseEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_environments",
                        to="apiData.apicase",
                        verbose_name="关联用例",
                    ),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_relations",
                        to="config.environment",
                        verbose_name="关联环境",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例环境关系表",
                "db_table": "case_environment",
                "unique_together": {("case", "environment")},
            },
        ),
        migrations.CreateModel(
            name="ProjectEnvironment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "environment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="project_relations",
                        to="config.environment",
                        verbose_name="关联环境",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_environments",
                        to="project.project",
                        verbose_name="关联项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "项目环境关系表",
                "db_table": "project_environment",
                "unique_together": {("project", "environment")},
            },
        ),
    ]
