# Generated by Django 5.2.3 on 2025-08-28 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0002_remove_environment_remark_remove_environment_url_and_more"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="caseenvironment",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_relations",
                to="config.environment",
                verbose_name="关联环境",
            ),
        ),
        migrations.AlterField(
            model_name="environment",
            name="name",
            field=models.CharField(max_length=32, verbose_name="环境名称"),
        ),
        migrations.AlterField(
            model_name="environment",
            name="type",
            field=models.IntegerField(
                choices=[(0, "局部环境"), (1, "全局环境")],
                help_text="0=局部环境, 1=全局环境",
                verbose_name="环境类型",
            ),
        ),
        migrations.AlterField(
            model_name="projectenvironment",
            name="environment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_relations",
                to="config.environment",
                verbose_name="关联环境",
            ),
        ),
        migrations.AlterField(
            model_name="projectenvironment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_environments",
                to="project.project",
                verbose_name="关联项目",
            ),
        ),
    ]
