# Generated by Django 5.2.4 on 2025-08-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0003_add_environment"),
    ]

    operations = [
        # 只保留添加 url 字段的操作
        migrations.AddField(
            model_name="environment",
            name="url",
            field=models.CharField(
                default="http://example.com", max_length=255, verbose_name="环境URL"
            ),
            preserve_default=False,
        ),
    ]
