# Generated by Django 5.2.3 on 2025-08-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0004_add_url_to_environment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfEnvir",
        ),
        migrations.AlterModelOptions(
            name="projectenvirdata",
            options={"verbose_name": "环境表"},
        ),
        migrations.AlterField(
            model_name="environment",
            name="url",
            field=models.CharField(max_length=255, null=True, verbose_name="环境URL"),
        ),
    ]
