# Generated by Django 5.2.4 on 2025-08-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("config", "0005_delete_confenvir_alter_projectenvirdata_options_and_more"),
    ]

    operations = [
        # 首先删除外键约束
        migrations.RemoveField(
            model_name='projectenvirdata',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectenvirdata',
            name='envir',
        ),
        # 然后删除表
        migrations.DeleteModel(
            name='ProjectEnvirData',
        ),
    ]
