# Generated by Django 5.2.4 on 2025-08-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiCase",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="测试用例名称")),
                ("status", models.IntegerField(default=0, verbose_name="执行结果")),
                ("remark", models.TextField(null=True, verbose_name="用例备注")),
                (
                    "report_data",
                    models.JSONField(null=True, verbose_name="测试报告数据"),
                ),
                ("is_deleted", models.BooleanField(default=0, verbose_name="是否删除")),
                (
                    "latest_run_time",
                    models.DateTimeField(null=True, verbose_name="最后一次执行时间"),
                ),
                ("position", models.IntegerField(default=0, verbose_name="排序优先级")),
            ],
            options={
                "verbose_name": "接口用例",
                "db_table": "api_case",
            },
        ),
        migrations.CreateModel(
            name="ApiCaseModule",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                (
                    "module_related",
                    models.JSONField(
                        default=list, verbose_name="所属模块级联关系（父子级）"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                ("position", models.IntegerField(default=0, verbose_name="排序优先级")),
            ],
            options={
                "verbose_name": "用例模块",
                "db_table": "api_case_module",
            },
        ),
        migrations.CreateModel(
            name="ApiCaseStep",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("api", "API"), ("sql", "SQL")],
                        default="api",
                        max_length=50,
                        verbose_name="步骤类型",
                    ),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "step_name",
                    models.CharField(
                        max_length=255, null=True, verbose_name="步骤名称"
                    ),
                ),
                (
                    "step_order",
                    models.PositiveIntegerField(default=1, verbose_name="步骤顺序"),
                ),
                (
                    "status",
                    models.IntegerField(default=0, null=True, verbose_name="执行状态"),
                ),
                (
                    "retried_times",
                    models.SmallIntegerField(null=True, verbose_name="重试次数"),
                ),
                (
                    "controller_data",
                    models.JSONField(null=True, verbose_name="步骤控制器"),
                ),
                ("params", models.JSONField(null=True, verbose_name="详细参数")),
                ("results", models.JSONField(null=True, verbose_name="步骤执行结果")),
                ("timeout", models.IntegerField(null=True, verbose_name="超时时间")),
                (
                    "source",
                    models.CharField(max_length=50, null=True, verbose_name="API来源"),
                ),
            ],
            options={
                "verbose_name": "api用例的步骤",
                "db_table": "api_case_step",
            },
        ),
        migrations.CreateModel(
            name="ApiForeachStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.PositiveIntegerField(verbose_name="步骤顺序")),
                (
                    "step_name",
                    models.CharField(
                        default="", max_length=255, verbose_name="步骤名称"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        default="case",
                        max_length=255,
                        verbose_name="执行参数类型(1.api2.case；3.SQL 4.header（取value） 5.var 6.host)",
                    ),
                ),
                ("status", models.IntegerField(default=0, verbose_name="执行状态")),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "controller_data",
                    models.JSONField(null=True, verbose_name="步骤控制器"),
                ),
                (
                    "retried_times",
                    models.SmallIntegerField(null=True, verbose_name="重试了几次"),
                ),
            ],
            options={
                "verbose_name": "api用例循环控制器步骤",
                "db_table": "api_foreach_step",
            },
        ),
        migrations.CreateModel(
            name="ApiModule",
            fields=[
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=12, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, verbose_name="模块名称")),
                (
                    "module_related",
                    models.JSONField(
                        default=list, verbose_name="所属模块级联关系（父子级）"
                    ),
                ),
            ],
            options={
                "verbose_name": "用例模块",
                "db_table": "api_module",
            },
        ),
    ]
