# Generated by Django 5.2.3 on 2025-08-26 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("apiData", "0001_initial"),
        ("config", "0001_initial"),
        ("project", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="apicase",
            name="creater",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建用户",
            ),
        ),
        migrations.AddField(
            model_name="apicase",
            name="env",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="config.environment",
                verbose_name="引用的环境",
            ),
        ),
        migrations.AddField(
            model_name="apicase",
            name="updater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_upd_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改用户",
            ),
        ),
        migrations.AddField(
            model_name="apicasemodule",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apiData.apicasemodule",
                verbose_name="父模块",
            ),
        ),
        migrations.AddField(
            model_name="apicase",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="apiData.apicasemodule",
                verbose_name="所属模块",
            ),
        ),
        migrations.AddField(
            model_name="apicasestep",
            name="case",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="case_step",
                to="apiData.apicase",
                verbose_name="所属测试用例",
            ),
        ),
        migrations.AddField(
            model_name="apicasestep",
            name="env",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="config.environment",
                verbose_name="环境变量",
            ),
        ),
        migrations.AddField(
            model_name="apicasestep",
            name="quote_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quoted_by_steps",
                to="apiData.apicase",
                verbose_name="引用的用例",
            ),
        ),
        migrations.AddField(
            model_name="apiforeachstep",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="apiData.apicase",
                verbose_name="关联的用例报告数据",
            ),
        ),
        migrations.AddField(
            model_name="apiforeachstep",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apiData.apiforeachstep",
                verbose_name="父循环步骤",
            ),
        ),
        migrations.AddField(
            model_name="apiforeachstep",
            name="quote_case",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_quote_case",
                to="apiData.apicase",
                verbose_name="引用的测试用例",
            ),
        ),
        migrations.AddField(
            model_name="apiforeachstep",
            name="step",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="apiData.apicasestep",
                verbose_name="所属测试步骤",
            ),
        ),
        migrations.AddField(
            model_name="apimodule",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="apiData.apimodule",
                verbose_name="父模块",
            ),
        ),
        migrations.AddField(
            model_name="apimodule",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
                verbose_name="关联项目",
            ),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="creater",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建用户",
            ),
        ),
        migrations.AddField(
            model_name="scheduledtask",
            name="updater",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="%(class)s_upd_user",
                to=settings.AUTH_USER_MODEL,
                verbose_name="修改用户",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apicase",
            unique_together={("name", "module")},
        ),
        migrations.AlterUniqueTogether(
            name="apicasestep",
            unique_together={("case", "step_order")},
        ),
        migrations.AlterUniqueTogether(
            name="apiforeachstep",
            unique_together={("step", "step_order")},
        ),
    ]
