# Generated by Django 5.2.3 on 2025-08-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apicasestep",
            old_name="env_id",
            new_name="env",
        ),
    ]
