# Generated by Django 5.2.3 on 2025-08-27 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0002_initial"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apimodule",
            options={"verbose_name": "用例模块(旧)"},
        ),
        migrations.AddField(
            model_name="apicasemodule",
            name="project",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.project",
                verbose_name="关联项目",
            ),
        ),
    ]
