# Generated by Django 5.2.3 on 2025-08-25 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0003_rename_env_id_apicasestep_env"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicasestep",
            name="quote_case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="quoted_by_steps",
                to="apiData.apicase",
                verbose_name="引用的用例",
            ),
        ),
    ]
