# Generated by Django 5.2.3 on 2025-08-27 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0003_alter_apimodule_options_apicasemodule_project"),
        ("project", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apicasemodule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="project.project",
                verbose_name="关联项目",
            ),
        ),
    ]
