# Generated by Django 5.2.3 on 2025-08-25 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0004_apicasestep_quote_case"),
        ("config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apicase",
            name="env",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="config.environment",
                verbose_name="引用的环境",
            ),
        ),
    ]
