# Generated by Django 5.2.4 on 2025-08-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0004_apicase_position_apicasemodule_position"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="apiforeachstep",
            options={"verbose_name": "api用例循环控制器步骤"},
        ),
        migrations.AlterField(
            model_name="apicasemodule",
            name="module_related",
            field=models.JSONField(
                default=list, verbose_name="所属模块级联关系（父子级）"
            ),
        ),
        migrations.AlterField(
            model_name="apimodule",
            name="module_related",
            field=models.JSONField(
                default=list, verbose_name="所属模块级联关系（父子级）"
            ),
        ),
    ]
