# Generated by Django 5.2.3 on 2025-08-28 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apiData", "0005_remove_apicase_report_data_report"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssertionRule",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("jsonpath", "JSONPath"),
                            ("regex", "Regular Expression"),
                            ("xpath", "XPath"),
                            ("header", "HTTP Header"),
                            ("status_code", "Status Code"),
                        ],
                        default="jsonpath",
                        max_length=50,
                        verbose_name="断言类型",
                    ),
                ),
                ("expression", models.TextField(verbose_name="断言表达式")),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("==", "等于"),
                            ("!=", "不等于"),
                            (">", "大于"),
                            ("<", "小于"),
                            (">=", "大于等于"),
                            ("<=", "小于等于"),
                            ("contains", "包含"),
                            ("not_contains", "不包含"),
                            ("starts_with", "开头是"),
                            ("ends_with", "结尾是"),
                            ("empty", "为空"),
                            ("not_empty", "不为空"),
                            ("null", "为null"),
                            ("not_null", "不为null"),
                        ],
                        default="==",
                        max_length=20,
                        verbose_name="比较运算符",
                    ),
                ),
                (
                    "expected_value",
                    models.TextField(blank=True, null=True, verbose_name="预期值"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("enabled", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assertions",
                        to="apiData.apicasestep",
                        verbose_name="所属测试步骤",
                    ),
                ),
            ],
            options={
                "verbose_name": "API断言规则",
                "db_table": "api_assertion_rule",
            },
        ),
    ]
