# Generated by Django 5.2.3 on 2025-08-26 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.SmallAutoField(primary_key=True, serialize=False)),
                ("position", models.SmallIntegerField(default=1, verbose_name="排序")),
                (
                    "name",
                    models.CharField(max_length=100, unique=True, verbose_name="名称"),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "项目配置字典表",
                "db_table": "project",
                "ordering": ("position",),
            },
        ),
        migrations.CreateModel(
            name="ProjectParamType",
            fields=[
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                ("position", models.SmallIntegerField(default=1, verbose_name="排序")),
                (
                    "id",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="修改时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "参数类型表",
                "db_table": "project_param_type",
                "ordering": ("position",),
            },
        ),
    ]
