# Generated by Django 5.2.4 on 2025-08-20 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_add_projectparamtype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ConfParamType",
        ),
        migrations.AddField(
            model_name="project",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=0, verbose_name="创建时间"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="project",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="修改时间"
            ),
        ),
        migrations.AddField(
            model_name="projectparamtype",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="创建时间",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="projectparamtype",
            name="updated",
            field=models.DateTimeField(
                auto_now=True, null=True, verbose_name="修改时间"
            ),
        ),
        migrations.AlterModelTable(
            name="project",
            table="project",
        ),
    ]
