# Generated by Django 5.2.4 on 2025-08-20 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_add_time_fields"),
        (
            "project",
            "0005_delete_confparamtype_project_created_project_updated_and_more",
        ),
    ]

    operations = []
